---
- name: installing and launching filebeat
  hosts: webservers
  become: true
  tasks:

  - name: download filebeat
    command: curl -L -O http://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/filebeat-config.yml 
      dest: /etc/filebeat/filebeat.yml

  - name: setup filebeat
    command: service filebeat start

- name: enable service filebeat on boot
  systemd:
    name: filebeata
    enabled: yes